### ISSUE TITLE
Uncaught TypeError : Cannot read property  'top' of undefined

### ISSUE THREAD

**Issue by le61berthier** [alvarotrigo/fullPage.js#3289]
Hello,

Today, i had a strange error impossible to look where it's bad in my code:

Deferred exception: Cannot read property 'top' of undefined TypeError: Cannot read property 'top' of undefined
    at silentScroll (http://ledoigtdansloeil.fr/MultiScroll/js/jquery.multiscroll.js:352:82)
    at r.fn.init.<anonymous> (http://ledoigtdansloeil.fr/MultiScroll/js/jquery.multiscroll.js:185:4)
    at i (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:28017)
    at Object.add [as done] (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:28316)
    at r.fn.init.$.fn.multiscroll (http://ledoigtdansloeil.fr/MultiScroll/js/jquery.multiscroll.js:170:16)
    at HTMLDocument.<anonymous> (http://ledoigtdansloeil.fr/MultiScroll/index.php:97:34)
    at j (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:29999)
    at k (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:30313) undefined

=> I think the problem came from index.php: 97 which the code is 

				$(document).ready(function() {
line 97 =>>>             $('#multiscroll').multiscroll({
		             	sectionsColor: ['#FFFFFF', '#FFFFFF', '#FFFFFF'],

So since now, it doesn't recognize my div id. I don't know why. I've tried to delete each js code line by line and could't find the solution.
Is it possible that jquery

Any thoughts ?

**Comment by alvarotrigo** [comment]
Please open your issue together with an isolated reproduction in the [MultiScroll issues forum](https://github.com/alvarotrigo/multiScroll.js/issues).
This is only for fullpage.js.

And please read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).
