### ISSUE TITLE
Problem with licenseKey place

### ISSUE THREAD

**Issue by ivansteff** [alvarotrigo/fullPage.js#3581]
Hi, i have problem with licenseKey, i insert the script before the closing tag `</body>`

```
<script type="text/javascript">
$(document).ready(function() {
	$('#fullpage').fullpage({
        licenseKey: 'OPEN-SOURCE-GPLV3-LICENSE',
	autoScrolling:true,
	scrollHorizontally: true
	});

	//methods
	$.fn.fullpage.setAllowScrolling(false);
});
</script>
```
And have next erorr:
```
fullpage.js:3388 fullPage: Fullpage.js version 3 has changed its license to GPLv3 and it requires a `licenseKey` option. Read about it here:
showError @ fullpage.js:3388

fullpage.js:3388 fullPage: https://github.com/alvarotrigo/fullPage.js#options.
showError @ fullpage.js:3388

fullpage.js:3388 fullPage: fullpage.js extensions require fullpage.extensions.min.js file instead of the usual fullpage.js. Requested: scrollHorizontally
showError @ fullpage.js:3388

jquery.min.js:2 jQuery.Deferred exception: Cannot read property '0' of null TypeError: Cannot read property '0' of null
    at setBodyClass (http://localhost:3000/libs/fullpage.js:2772:53)
    at init (http://localhost:3000/libs/fullpage.js:609:13)
    at new initialise (http://localhost:3000/libs/fullpage.js:588:13)
    at r.fn.init.$.fn.fullpage (http://localhost:3000/libs/fullpage.js:3967:22)
    at HTMLDocument.<anonymous> (http://localhost:3000/:68:27)
    at j (http://localhost:3000/libs/jquery.min.js:2:29999)
    at k (http://localhost:3000/libs/jquery.min.js:2:30313) undefined
r.Deferred.exceptionHook @ jquery.min.js:2
jquery.min.js:2 Uncaught TypeError: Cannot read property '0' of null
    at setBodyClass (fullpage.js:2772)
    at init (fullpage.js:609)
    at new initialise (fullpage.js:588)
    at r.fn.init.$.fn.fullpage (fullpage.js:3967)
    at HTMLDocument.<anonymous> ((index):68)
    at j (jquery.min.js:2)
    at k (jquery.min.js:2)
10fullpage.js:3475 Uncaught TypeError: Cannot read property 'nextElementSibling' of undefined
    at until (fullpage.js:3475)
    at nextUntil (fullpage.js:3494)
    at moveSectionDown (fullpage.js:401)
    at scrolling (fullpage.js:1229)
    at HTMLDocument.MouseWheelHandler (fullpage.js:1405)
```

**Comment by alvarotrigo** [comment]
That means exactly what it says in the error message link:

> Fullpage.js version 3 has changed its license to GPLv3 and it requires a `licenseKey` option. Read about it here: https://github.com/alvarotrigo/fullPage.js#options.

Which is:

> licenseKey: (default null). This option is compulsory. If you use fullPage in a non open source project, then you should use the license key provided on the purchase of the fullPage Commercial License. If your project is open source, contact me with a link to its repository and I'll provide you a license key. Please read more about licenses here and on the website. For example:

So basically, rather you acquire a license from [the pricing page](https://alvarotrigo.com/fullPage/pricing/) or you [contact me](https://alvarotrigo.com/#contact) for an open source license.
