### ISSUE TITLE
Uncaught TypeError: t is not a function

### ISSUE THREAD

**Issue by imarkdesigns** [alvarotrigo/fullPage.js#4591]
I've made a purchased and activated the license key. But when I tried scrolling by using the extension of "scrollHorizontally" it gives me this javascript error. I'm using this in my WordPress staging site from Kinsta.

```
Uncaught TypeError: t is not a function fullpage.extensions.min.js:11
at Fi (fullpage.extensions.min.js:11:39238)
at HTMLDocument.Mo (fullpage.extensions.min.js:11:45417)
```

I have the assets file in place:
```
<script type="text/javascript" src="/resources/scripts/fullpage/fullpage.scrollHorizontally.min.js"></script>
<script type="text/javascript" src="/resources/scripts/fullpage/fullpage.extensions.min.js"></script>
```

and here's my init:
```
new fullpage('#sgg-section', {

    // Options
    menu: '#main-menu',
    lockAnchors: false,
    anchors: ['home', 'aboutSGG', 'adsPosting', 'onlineQuote', 'microInfluencer', 'livedrivestream', 'franchiseAds', 'followersChart', 'adsGraph', 'managementTeam', 'contactInfo', 'footer'],
    navigation: true,
    navigationPosition: 'left',
    navigationTooltips: ['Home', 'About SGG Media', 'SGG Media Ads Postings', 'Online Quote', 'What is a Micro Influencer', 'Live Drive Stream', 'Franchise Advertising', 'SGG Media Followers', 'Social Media Chart', 'Management Team', 'Contact'],
    showActiveTooltip: false,
    slidesNavigation: true,
    controlArrows: false,
    scrollingSpeed: 1000,
    paddingTop: '80px',
    credits: { 
        enabled: false, 
        label: 'Made with fullPage.js', 
        position: 'right'
    },
    afterLoad: function(origin, destination, direction, trigger){
        var origin = this;

        if(destination.anchor == 'onlineQuote'){
            jQuery('#quote-ads').hide();
        } else {
            jQuery('#quote-ads').show();
        }
    },

    // License
    // licenseKey: 'xxxxxxxxx',
    autoScrolling: true,

    // Extension
    scrollHorizontallyKey: 'xxxxxxxxxxxxxxxxx',
    scrollHorizontally: true,
});
```

any problem in my code? thanks!

**Comment by alvarotrigo** [comment]
Make sure  you are using the latest version of fullpage.js (4.0.20) for both files, the JS and the CSS one.
And that your extension is for v4.

If you still have issues, you can provide us with your URL and more details using the [contact form](https://alvarotrigo.com/contact/).

**Comment by imarkdesigns** [comment]
yeah, i have all the files in latest versions.
css & js: 4.0.20 
ext: fullpage.js Scroll Horizontally Extension 0.0.4 for fullPage.js v3
